[2022-12-11T16:30:08.911+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: hard_dag.file_exist scheduled__2022-12-10T16:34:00+00:00 [queued]>
[2022-12-11T16:30:08.925+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: hard_dag.file_exist scheduled__2022-12-10T16:34:00+00:00 [queued]>
[2022-12-11T16:30:08.925+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-12-11T16:30:08.925+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-12-11T16:30:08.926+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-12-11T16:30:08.940+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): file_exist> on 2022-12-10 16:34:00+00:00
[2022-12-11T16:30:08.944+0000] {standard_task_runner.py:55} INFO - Started process 26699 to run task
[2022-12-11T16:30:08.948+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'hard_dag', 'file_exist', 'scheduled__2022-12-10T16:34:00+00:00', '--job-id', '7601', '--raw', '--subdir', 'DAGS_FOLDER/hard_dag.py', '--cfg-path', '/tmp/tmp6vx3udtk']
[2022-12-11T16:30:08.948+0000] {standard_task_runner.py:83} INFO - Job 7601: Subtask file_exist
[2022-12-11T16:30:09.011+0000] {task_command.py:376} INFO - Running <TaskInstance: hard_dag.file_exist scheduled__2022-12-10T16:34:00+00:00 [running]> on host 5663d391ad54
[2022-12-11T16:30:09.080+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=hard_dag
AIRFLOW_CTX_TASK_ID=file_exist
AIRFLOW_CTX_EXECUTION_DATE=2022-12-10T16:34:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-10T16:34:00+00:00
[2022-12-11T16:30:09.095+0000] {base.py:71} INFO - Using connection ID 'postgre_con' for task execution.
[2022-12-11T16:30:09.115+0000] {sql.py:315} INFO - Running statement: CREATE TABLE if not exists rnd_table (id serial PRIMARY KEY, value_1 integer, value_2 integer), parameters: None
[2022-12-11T16:30:09.126+0000] {base.py:71} INFO - Using connection ID 'postgre_con' for task execution.
[2022-12-11T16:30:09.156+0000] {sql.py:315} INFO - Running statement: truncate rnd_table, parameters: None
[2022-12-11T16:30:09.181+0000] {logging_mixin.py:137} INFO - INSERT INTO rnd_table (value_1,value_2) VALUES (9, 7)
[2022-12-11T16:30:09.188+0000] {base.py:71} INFO - Using connection ID 'postgre_con' for task execution.
[2022-12-11T16:30:09.205+0000] {sql.py:315} INFO - Running statement: INSERT INTO rnd_table (value_1,value_2) VALUES (9, 7), parameters: None
[2022-12-11T16:30:09.209+0000] {sql.py:324} INFO - Rows affected: 1
[2022-12-11T16:30:09.212+0000] {logging_mixin.py:137} INFO - INSERT INTO rnd_table (value_1,value_2) VALUES (9, 6)
[2022-12-11T16:30:09.218+0000] {base.py:71} INFO - Using connection ID 'postgre_con' for task execution.
[2022-12-11T16:30:09.238+0000] {sql.py:315} INFO - Running statement: INSERT INTO rnd_table (value_1,value_2) VALUES (9, 6), parameters: None
[2022-12-11T16:30:09.242+0000] {sql.py:324} INFO - Rows affected: 1
[2022-12-11T16:30:09.248+0000] {python.py:177} INFO - Done. Returned value was: None
[2022-12-11T16:30:09.257+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=hard_dag, task_id=file_exist, execution_date=20221210T163400, start_date=20221211T163008, end_date=20221211T163009
[2022-12-11T16:30:09.284+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2022-12-11T16:30:09.305+0000] {taskinstance.py:2623} INFO - 1 downstream tasks scheduled from follow-on schedule check
