[2022-12-11T16:34:08.737+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: hard_dag.file_exist scheduled__2022-12-11T16:33:00+00:00 [queued]>
[2022-12-11T16:34:08.750+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: hard_dag.file_exist scheduled__2022-12-11T16:33:00+00:00 [queued]>
[2022-12-11T16:34:08.751+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-12-11T16:34:08.751+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-12-11T16:34:08.751+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-12-11T16:34:08.766+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): file_exist> on 2022-12-11 16:33:00+00:00
[2022-12-11T16:34:08.770+0000] {standard_task_runner.py:55} INFO - Started process 26985 to run task
[2022-12-11T16:34:08.774+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'hard_dag', 'file_exist', 'scheduled__2022-12-11T16:33:00+00:00', '--job-id', '7649', '--raw', '--subdir', 'DAGS_FOLDER/hard_dag.py', '--cfg-path', '/tmp/tmpuc5er6vc']
[2022-12-11T16:34:08.774+0000] {standard_task_runner.py:83} INFO - Job 7649: Subtask file_exist
[2022-12-11T16:34:08.842+0000] {task_command.py:376} INFO - Running <TaskInstance: hard_dag.file_exist scheduled__2022-12-11T16:33:00+00:00 [running]> on host 5663d391ad54
[2022-12-11T16:34:08.936+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=hard_dag
AIRFLOW_CTX_TASK_ID=file_exist
AIRFLOW_CTX_EXECUTION_DATE=2022-12-11T16:33:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-11T16:33:00+00:00
[2022-12-11T16:34:08.956+0000] {base.py:71} INFO - Using connection ID 'postgre_con' for task execution.
[2022-12-11T16:34:08.981+0000] {sql.py:315} INFO - Running statement: CREATE TABLE if not exists rnd_table (id serial PRIMARY KEY, value_1 integer, value_2 integer), parameters: None
[2022-12-11T16:34:08.998+0000] {base.py:71} INFO - Using connection ID 'postgre_con' for task execution.
[2022-12-11T16:34:09.051+0000] {sql.py:315} INFO - Running statement: truncate rnd_table, parameters: None
[2022-12-11T16:34:09.080+0000] {logging_mixin.py:137} INFO - INSERT INTO rnd_table (value_1,value_2) VALUES (9, 7)
[2022-12-11T16:34:09.089+0000] {base.py:71} INFO - Using connection ID 'postgre_con' for task execution.
[2022-12-11T16:34:09.111+0000] {sql.py:315} INFO - Running statement: INSERT INTO rnd_table (value_1,value_2) VALUES (9, 7), parameters: None
[2022-12-11T16:34:09.117+0000] {sql.py:324} INFO - Rows affected: 1
[2022-12-11T16:34:09.121+0000] {logging_mixin.py:137} INFO - INSERT INTO rnd_table (value_1,value_2) VALUES (9, 6)
[2022-12-11T16:34:09.128+0000] {base.py:71} INFO - Using connection ID 'postgre_con' for task execution.
[2022-12-11T16:34:09.157+0000] {sql.py:315} INFO - Running statement: INSERT INTO rnd_table (value_1,value_2) VALUES (9, 6), parameters: None
[2022-12-11T16:34:09.163+0000] {sql.py:324} INFO - Rows affected: 1
[2022-12-11T16:34:09.168+0000] {logging_mixin.py:137} INFO - INSERT INTO rnd_table (value_1,value_2) VALUES (8, 2)
[2022-12-11T16:34:09.177+0000] {base.py:71} INFO - Using connection ID 'postgre_con' for task execution.
[2022-12-11T16:34:09.200+0000] {sql.py:315} INFO - Running statement: INSERT INTO rnd_table (value_1,value_2) VALUES (8, 2), parameters: None
[2022-12-11T16:34:09.206+0000] {sql.py:324} INFO - Rows affected: 1
[2022-12-11T16:34:09.211+0000] {logging_mixin.py:137} INFO - INSERT INTO rnd_table (value_1,value_2) VALUES (1, 0)
[2022-12-11T16:34:09.221+0000] {base.py:71} INFO - Using connection ID 'postgre_con' for task execution.
[2022-12-11T16:34:09.247+0000] {sql.py:315} INFO - Running statement: INSERT INTO rnd_table (value_1,value_2) VALUES (1, 0), parameters: None
[2022-12-11T16:34:09.253+0000] {sql.py:324} INFO - Rows affected: 1
[2022-12-11T16:34:09.256+0000] {logging_mixin.py:137} INFO - INSERT INTO rnd_table (value_1,value_2) VALUES (1, 0)
[2022-12-11T16:34:09.262+0000] {base.py:71} INFO - Using connection ID 'postgre_con' for task execution.
[2022-12-11T16:34:09.300+0000] {sql.py:315} INFO - Running statement: INSERT INTO rnd_table (value_1,value_2) VALUES (1, 0), parameters: None
[2022-12-11T16:34:09.306+0000] {sql.py:324} INFO - Rows affected: 1
[2022-12-11T16:34:09.309+0000] {logging_mixin.py:137} INFO - INSERT INTO rnd_table (value_1,value_2) VALUES (6, 3)
[2022-12-11T16:34:09.318+0000] {base.py:71} INFO - Using connection ID 'postgre_con' for task execution.
[2022-12-11T16:34:09.340+0000] {sql.py:315} INFO - Running statement: INSERT INTO rnd_table (value_1,value_2) VALUES (6, 3), parameters: None
[2022-12-11T16:34:09.346+0000] {sql.py:324} INFO - Rows affected: 1
[2022-12-11T16:34:09.359+0000] {python.py:177} INFO - Done. Returned value was: None
[2022-12-11T16:34:09.369+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=hard_dag, task_id=file_exist, execution_date=20221211T163300, start_date=20221211T163408, end_date=20221211T163409
[2022-12-11T16:34:09.396+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2022-12-11T16:34:09.419+0000] {taskinstance.py:2623} INFO - 1 downstream tasks scheduled from follow-on schedule check
